version: "3.9"
services:
  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend

  reverse-proxy:
    build:
      context: ./reverse-proxy

  kali:
    build:
      context: ./kali
    environment:
      - VNC_PW=password
    ports:
      - 6901:6901
